default = "3.5-inch 1.44M"

#
# Array of supported floppy drives
#
[[drive]]
    name = "5.25-inch 180K"
    cyls = 40
    heads = 1
    rpm = 300
    maxkbps = 250
    images = [
        "MS-DOS 180K Single Side",
        "MS-DOS 160K Single Side",
    ]
[[drive]]
    name = "5.25-inch 360K"
    cyls = 40
    heads = 2
    rpm = 300
    maxkbps = 250
    images = [
        "MS-DOS 360K",
        "MS-DOS 400K",
        "MS-DOS 320K",
        "MS-DOS 180K Single Side",
        "MS-DOS 160K Single Side",
    ]
[[drive]]
    name = "5.25-inch 720K"
    cyls = 80
    heads = 2
    rpm = 300
    maxkbps = 250
    images = [
        "MS-DOS 720K",
        "MS-DOS 800K",
        "MS-DOS 360K Stretch",
        "MS-DOS 400K Stretch",
        "MS-DOS 320K Stretch",
        "MS-DOS 360K Single Side",
        "MS-DOS 400K Single Side",
        "MS-DOS 180K Single Side",
        "MS-DOS 160K Single Side",
        "Amiga 880K",
        "BK-0010 800K",
    ]
[[drive]]
    name = "5.25-inch 1.2M"
    cyls = 80
    heads = 2
    rpm = 360
    maxkbps = 500
    images = [
        "MS-DOS 1.2M",
    ]
[[drive]]
    name = "3.5-inch 360K"
    cyls = 80
    heads = 1
    rpm = 300
    maxkbps = 250
    images = [
        "MS-DOS 360K Single Side",
        "MS-DOS 400K Single Side",
    ]
[[drive]]
    name = "3.5-inch 720K"
    cyls = 80
    heads = 2
    rpm = 300
    maxkbps = 250
    images = [
        "MS-DOS 720K",
        "MS-DOS 800K",
        "MS-DOS 360K Single Side",
        "MS-DOS 400K Single Side",
        "Amiga 880K",
        "BK-0010 800K",
    ]
[[drive]]
    name = "3.5-inch 1.44M"
    cyls = 80
    heads = 2
    rpm = 300
    maxkbps = 500
    images = [
        "MS-DOS 1.44M",
        "MS-DOS 1.6M",
        "MS-DOS 720K",
        "MS-DOS 800K",
        "MS-DOS 360K Single Side",
        "MS-DOS 400K Single Side",
        "Linux 1.44M",
        "BSD 1.44M",
        "Amiga 880K",
        "BK-0010 800K",
    ]
[[drive]]
    name = "3.5-inch 2.88M"
    cyls = 80
    heads = 2
    rpm = 300
    maxkbps = 1000
    images = [
        "IBM ED 2.88M",
        "IBM ED 3.12M",
        "MS-DOS 1.44M",
        "MS-DOS 1.6M",
        "MS-DOS 720K",
        "MS-DOS 800K",
        "MS-DOS 360K Single Side",
        "MS-DOS 400K Single Side",
        "Linux 1.44M",
        "BSD 1.44M",
        "Amiga 880K",
        "BK-0010 800K",
    ]

#
# Array of built-in images for 'format' command
#
[[image]]
    name = "MS-DOS 160K Single Side"
    file = "fat160.img"
[[image]]
    name = "MS-DOS 180K Single Side"
    file = "fat180.img"
[[image]]
    name = "MS-DOS 360K Single Side"
    file = "fat360.img"
[[image]]
    name = "MS-DOS 400K Single Side"
    file = "fat400.img"
[[image]]
    name = "MS-DOS 320K"
    file = "fat320.img"
[[image]]
    name = "MS-DOS 360K"
    file = "fat360.img"
[[image]]
    name = "MS-DOS 400K"
    file = "fat400.img"
[[image]]
    name = "MS-DOS 720K"
    file = "fat720.img"
[[image]]
    name = "MS-DOS 800K"
    file = "fat800.img"
[[image]]
    name = "MS-DOS 1.2M"
    file = "fat1.2.img"
[[image]]
    name = "MS-DOS 1.44M"
    file = "fat1.44.img"
[[image]]
    name = "MS-DOS 1.6M"
    file = "fat1.6.img"
[[image]]
    name = "IBM ED 2.88M"
    file = "fat2.88.img"
[[image]]
    name = "IBM ED 3.12M"
    file = "fat3.12.img"
[[image]]
    name = "Linux 1.44M"
    file = "linux1.44.img"
[[image]]
    name = "BSD 1.44M"
    file = "bsd1.44.img"
[[image]]
    name = "Amiga 880K"
    file = "blank.adf"
[[image]]
    name = "BK-0010 800K"
    file = "andos.bkd"
